# -*- coding: utf-8 -*-
"""
main_nonlinear.py
[FINAL] 
1. 3D Traction Fix: Splits node sets into element faces automatically.
2. Log Fix: Correctly prints '3D Condition' or 'Plane Strain' based on dimension.
"""
from __future__ import annotations
import os, sys, importlib
from typing import Tuple, List, Dict
import numpy as np
import importlib.util

from Preprocessing_export_inp import Mesh
from Element_formulation_export_inp import Shape_Function
import nonlinear_hyper as nh
import importlib
nh = importlib.reload(nh)  # 수정한 내용을 반영하기 위해 reload
NonlinearHyper = nh.NonlinearHyper
from make_vtk import open_in_paraview


def _enu_to_mu_lam(E: float, nu: float) -> Tuple[float, float]:
    mu = E / (2.0 * (1.0 + nu))
    if abs(nu - 0.5) < 1e-9: lam = 1e8 * mu 
    else: lam = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu))
    return float(mu), float(lam)

def _import_main_setting(main_py_name: str = "main.py"):
    script_dir = os.path.dirname(os.path.abspath(__file__))
    main_path = os.path.join(script_dir, main_py_name)
    if not os.path.exists(main_path): main_path = os.path.join(os.getcwd(), main_py_name)
    spec = importlib.util.spec_from_file_location("user_main", main_path)
    user_main_module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(user_main_module)
    return user_main_module, user_main_module.setting

def write_vtk_custom(filepath, nodes, conn, u_disp, field_data={}):
    n_nodes = len(nodes); n_elems = len(conn); dim = nodes.shape[1]
    npe = len(conn[0]); cell_type = 0
    if dim == 2:
        if npe == 3: cell_type = 5
        elif npe == 4: cell_type = 9
        elif npe == 6: cell_type = 22
        elif npe == 8: cell_type = 23
    elif dim == 3:
        if npe == 4: cell_type = 10
        elif npe == 8: cell_type = 12
        elif npe == 10: cell_type = 24
        elif npe == 20: cell_type = 25

    with open(filepath, 'w') as f:
        f.write("# vtk DataFile Version 3.0\nGenerated by NonlinearHyper\nASCII\nDATASET UNSTRUCTURED_GRID\n")
        f.write(f"POINTS {n_nodes} double\n")
        for i in range(n_nodes):
            x, y = nodes[i, 0], nodes[i, 1]
            z = nodes[i, 2] if dim == 3 else 0.0
            f.write(f"{x:.6f} {y:.6f} {z:.6f}\n")
        f.write(f"\nCELLS {n_elems} {n_elems * (npe + 1)}\n")
        for c in conn: f.write(f"{npe} " + " ".join(map(str, c)) + "\n")
        f.write(f"\nCELL_TYPES {n_elems}\n")
        for _ in range(n_elems): f.write(f"{cell_type}\n")
        
        f.write(f"\nPOINT_DATA {n_nodes}\n")
        f.write("VECTORS Displacement double\n")
        for i in range(n_nodes):
            ux, uy = u_disp[i, 0], u_disp[i, 1]
            uz = u_disp[i, 2] if u_disp.shape[1] == 3 else 0.0
            f.write(f"{ux:.6e} {uy:.6e} {uz:.6e}\n")
            
        for name, data in field_data.items():
            if len(data) == n_nodes:
                f.write(f"\nSCALARS {name} double 1\nLOOKUP_TABLE default\n")
                for val in data: f.write(f"{val:.6e}\n")

# -----------------------------------------------------------------------------
# Traction Generation Helpers
# -----------------------------------------------------------------------------

def _make_traction_edges_2d(setting, NL, conn): 
    traction_list = getattr(setting, "traction_list_3d", [])
    if not traction_list: return []
    edge_defs = [(0,1,4),(1,2,5),(2,3,6),(3,0,7)] if len(conn[0])==8 else [(0,1,None),(1,2,None),(2,3,None),(3,0,None)]
    if len(conn[0]) == 3: edge_defs = [(0,1,None),(1,2,None),(2,0,None)]

    edges = []
    for it in traction_list:
        ns = set(n-1 if 0 not in it["nodes"] else n for n in it["nodes"])
        T = it.get("traction", [0,0,0])[:2]
        P = it.get("pressure", None)
        for e_idx, c in enumerate(conn):
            for n1,n2,m in edge_defs:
                if n1 < len(c) and n2 < len(c) and c[n1] in ns and c[n2] in ns:
                    data = {"element": e_idx}
                    if m is not None and m < len(c): data["nodes3"] = (c[n1]+1,c[m]+1,c[n2]+1)
                    else: data["nodes"] = (c[n1]+1,c[n2]+1)
                    if P is not None: data["pressure"] = P
                    else: data["T"] = T
                    edges.append(data)
    return edges

def _make_traction_faces_3d(setting, NL, conn):
    """
    Splits node list into element faces for 3D integration (Hex/Tet).
    """
    traction_list = getattr(setting, "traction_list_3d", [])
    if not traction_list: return []
    
    npe = len(conn[0])
    
    # Define Face Topology
    if npe >= 8: # Hex
        face_defs = [
            (0,1,2,3), (4,5,6,7), 
            (0,1,5,4), (1,2,6,5), 
            (2,3,7,6), (3,0,4,7)
        ]
    elif npe >= 4: # Tet
        face_defs = [
            (0,1,2), (0,3,1), (1,3,2), (2,3,0)
        ]
    else:
        return []

    faces = []
    for it in traction_list:
        # Convert user input nodes (1-based) to 0-based set for check
        ns = set(n-1 for n in it["nodes"])
        
        val_t = it.get("traction", None)
        val_p = it.get("pressure", None)
        
        for e_idx, c in enumerate(conn):
            for f_nodes_idx in face_defs:
                # Global node IDs for this face
                face_global_ids = [c[idx] for idx in f_nodes_idx]
                
                # If all nodes of this face are in the traction set
                if all(nid in ns for nid in face_global_ids):
                    data = {
                        "nodes": [n+1 for n in face_global_ids], # 1-based for Solver
                        "element": e_idx
                    }
                    if val_p is not None: 
                        data["type"] = "pressure"
                        data["value"] = val_p
                    else: 
                        data["type"] = "traction"
                        data["value"] = val_t if val_t else [0,0,0]
                    faces.append(data)
    return faces


# -----------------------------------------------------------------------------
# Main Routine
# -----------------------------------------------------------------------------

def run_hyperelastic_analysis(setting):
    # 1. Mesh 로드 및 초기 설정
    mesh = Mesh.from_inp(getattr(setting, "inp_path", ""), debug=False)
    NL, conn = mesh.NL, np.asarray(mesh.conn, int)
    # 1-based 인덱싱 보정
    if np.min(conn) == 1: conn = conn - 1
    dim = NL.shape[1]
    
    print(f"\n[RUN] Nonlinear Hyperelastic Analysis ({dim}D)")
    print(f"[RUN] Mesh: {len(NL)} nodes, {len(conn)} elements")
    
    mu, lam = _enu_to_mu_lam(float(setting.E), float(setting.nu))
    sf = Shape_Function(None, setting.element_order, setting.element_shape, setting.integration)
    
    # Plane Stress 확인 및 로그 출력
    is_plane_stress = (getattr(setting, "analytical_conditions", "").lower().strip() == "plane stress")
    
    if dim == 2:
        if is_plane_stress:
            print("  - Condition: Plane Stress")
        else:
            print("  - Condition: Plane Strain")
    else:
        print("  - Condition: 3D Continuum")

    # 2. 비선형 모델 객체 생성
    model = NonlinearHyper(NL, conn, setting.element_shape, setting.element_order, setting.integration,
                           float(setting.thickness), sf, {"mu":mu,"lam":lam}, is_plane_stress, dim=dim)

    # -------------------------------------------------------------
    # [핵심 수정] 경계조건 분리 로드 및 통합
    # -------------------------------------------------------------
    
    # (1) 고정 조건 (0.0) 로드
    dirichlet_fixed = {}
    for it in getattr(setting, "dirichlet_list_3d", []):
        dirichlet_fixed[int(it[0])] = tuple(it[1:])

    # (2) 강제 변위 조건 (Not 0.0) 로드
    dirichlet_disp = {}
    for it in getattr(setting, "displacement_list_3d", []):
        dirichlet_disp[int(it[0])] = tuple(it[1:])

    # (3) 로그 출력 (사용자 확인용으로 분리해서 보여줌)
    print(f"  - Dirichlet BCs (fixed): {len(dirichlet_fixed)} nodes")
    print(f"  - Prescribed displacement BCs: {len(dirichlet_disp)} nodes")

    # (4) 솔버 입력용 통합 (NonlinearHyper는 하나의 딕셔너리로 처리하므로 합침)
    # ** 주의: 키가 겹칠 경우 뒤에 오는 dirichlet_disp 값이 우선 적용됨
    solver_dirichlet_input = {**dirichlet_fixed, **dirichlet_disp}
    # -------------------------------------------------------------

    # Traction / Body Force 처리
    if dim == 2: 
        tr_data = _make_traction_edges_2d(setting, NL, conn)
        b0 = getattr(setting, "body_force_vec_2d", (0,0))
    else: 
        tr_data = _make_traction_faces_3d(setting, NL, conn)
        b0 = getattr(setting, "body_force_vec_3d", (0,0,0))
        
    print(f"  - Traction/Pressure Items: {len(tr_data)} faces/edges generated.")

    # 집중 하중 처리
    conc = []
    for it in getattr(setting, "concentrated_force_list_3d", []):
        for n in it["nodes"]: 
            conc.append({"node": n, "F": it["F"]})
    
    # 3. 솔버 실행
    # [중요] 첫 번째 인자로 통합된 'solver_dirichlet_input'을 전달합니다.
    u = model.solve(
        solver_dirichlet_input,
        int(getattr(setting, "nsteps", 20)),
        float(getattr(setting, "atol", 1e-8)),
        float(getattr(setting, "rtol", 1e-8)),
        float(getattr(setting, "stol", 1e-8)),
        int(getattr(setting, "max_iter", 60)),
        b0,
        tr_data,
        conc,
        verbose=True,
        mode=str(getattr(setting, "nonlinear_mode", "fenics")),
        adapt_steps=bool(getattr(setting, "adaptive", False)),
    )

    # 4. 후처리 및 VTK 저장
    print("[VTK] Calculating Stresses...")
    _, S_nodes = model.compute_postprocessing_stresses(u)
    
    field_data = {}
    U_vec = np.column_stack([u[0::dim], u[1::dim], u[2::dim]]) if dim==3 else np.column_stack([u[0::2], u[1::2], np.zeros(len(NL))])
    field_data["UMAG"] = np.linalg.norm(U_vec, axis=1)
    
    if dim == 2:
        field_data["S11"], field_data["S22"], field_data["S33"], field_data["S12"] = S_nodes[:,0], S_nodes[:,1], S_nodes[:,2], S_nodes[:,3]
        field_data["Mises"] = S_nodes[:,4]
    else:
        field_data["S11"], field_data["S22"], field_data["S33"] = S_nodes[:,0], S_nodes[:,1], S_nodes[:,2]
        field_data["S12"], field_data["S13"], field_data["S23"] = S_nodes[:,3], S_nodes[:,4], S_nodes[:,5]
        field_data["Mises"] = S_nodes[:,6]

    out_dir = os.path.join(os.getcwd(), "results"); os.makedirs(out_dir, exist_ok=True)
    vtk_path = os.path.join(out_dir, getattr(setting, "vtk_filename", "result.vtk"))
    write_vtk_custom(vtk_path, NL, conn, U_vec, field_data)
    print(f"[VTK] Saved: {vtk_path}")
    
    if getattr(setting, "auto_open_paraview", True):
        try: open_in_paraview(vtk_path)
        except: pass

def run_from_setting():
    user_main, setting = _import_main_setting()
    run_hyperelastic_analysis(setting)

if __name__ == "__main__":
    run_from_setting()